---
title: "ES Homework"
author: "Jacob Lo"
date: "2015年12月14日"
output: html_document
---


```{r, echo=FALSE}
#preparation
install.packages("dplyr")
install.packages("nycflights13")
install.packages("ggplot2")
library(dplyr)
library(nycflights13)
library(ggplot2)
```

```{r}
# conditional filter to vector
x <- c(1,2,3,4,5)
y <- c(2,3,9,29,98)
y[y<mean(x)]
```

```{r}
#aggregated function and group by list
family1 <- list(
  name = "Espinoza",
  numofchild = 4,
  ages = c(5,7,9,11),
  measles = c("Y","N","Y","Y")
)
family2 <- list(
  name = "Ginsberg",
  numofchild = 3,
  ages = c(9,13,18),
  measles = c("Y","N","Y")
)

sapply(c(family1[3],family2[3]),function(i){ mean(i)})

```

```{r}
#add a new column in dataframe
add_flights <- mutate(flights,speed = distance / air_time * 60)
add_flights
```

```{r}
#count flight per day
daily <- group_by(flights,year,month,day)
summarise(daily, flight=n())
```

```{r}
#INSTALL GGPLOT2 IS GOD DAMM LONG
remove.packages(c("ggplot2", "data.table"))
install.packages('Rcpp', dependencies = TRUE)
install.packages('ggplot2', dependencies = TRUE)
install.packages('data.table', dependencies = TRUE)
#install.packages("ggplot2", dependencies=c("Depends", "Imports", "Suggests") )
```

```{r plot, fig.height=4,fig.height=3,message=FALSE}
data("mtcars") 
attach(mtcars)
#simple scatter plot
plot(wt~mpg,main="scatter plot",xlab = "car weight",ylab = "miles per gallon",pch=5)
my.cars.melted <- melt(my.cars, id.vars = "Car")
```

```{r plot, fig.height=4,fig.height=3,message=FALSE}
#Broken-line graph
plot(wt,mpg,type="l",main="scatter plot",xlab = "car weight",ylab = "miles per gallon",pch=5)
my.cars.melted <- melt(my.cars, id.vars = "Car")
```

```{r barplot, fig.height=4,fig.height=3,message=FALSE}
#Bar-plot graph
barplot(table(cyl),ylab="count")
```

```{r boxplot, fig.height=4,fig.height=3,message=FALSE}
#Boxplot
boxplot(mpg~cyl,main="car milage data",xlab="number of cylinders",ylab="miles per gallon")
```


